name: islamic
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.4
  flutter_bloc: ^8.1.4
  pretty_dio_logger: ^1.3.1
  dio: ^5.4.1
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  conditional_builder_null_safety: ^0.0.6
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  get_it: ^7.6.7
  flutter_phoenix: ^1.1.1
  wakelock: ^0.6.2
  youtube_player_flutter: ^8.1.2
  flutter_svg: ^2.0.9
  geocoding: ^2.1.1
  location: ^5.0.3
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  dots_indicator: ^3.0.0
  # youtube_player_flutter:
  # dots_indicator:
  # flutter_svg:
  # build_runner:
  # dartz:
  # shared_preferences:
  # get_it:
  # easy_localization:
  # flutter_phoenix:
  # flutter_bloc:
  # equatable:
  # flutter_screenutil:
  # conditional_builder_null_safety:
  # json_serializable:
  # json_annotation:
  # floor:
  # floor_generator:
  # sqlite3_flutter_libs:
  # retrofit:
  # retrofit_generator:
  # dio:
  # pretty_dio_logger:
  # internet_connection_checker:
  # location:
  # geocoding:
  # wakelock:
  # url_launcher:
  # google_fonts:
  # sqflite:





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/quran/
    - assets/json/
    - assets/translations/
    - assets/images/pillars/


  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 400
    - family: UthmanTN
      fonts:
        - asset: assets/fonts/UthmanTNB.ttf
          weight: 700
        - asset: assets/fonts/UthmanTN.ttf
          weight: 400
    - family: me_quran
      fonts:
        - asset: assets/fonts/me_quran.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/Hafs.ttf
